config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=staticfiles_storage.url("dsfr/dist/favicon/favicon.ico")
        ),
    ),
    path("admin/", admin.site.urls),
    # The "django-dsfr/" prefix is here because this site is deployed as doc on
    # https://numerique-gouv.github.io/django-dsfr/
    path("django-dsfr/", include("example_app.urls")),
    path("", RedirectView.as_view(pattern_name="index", permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dsfr/models.py
import os


from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from dsfr.constants import DJANGO_DSFR_LANGUAGES, NOTICE_TYPE_CHOICES


def validate_image_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = [".jpg", ".jpeg", ".png", ".svg"]
    if ext.lower() not in valid_extensions:
        raise ValidationError("Unsupported file extension.")


class DsfrConfig(models.Model):
    language = models.CharField(
        _("Language"),
        max_length=7,
        choices=DJANGO_DSFR_LANGUAGES,
        help_text=_("Only one configuration is allowed per language"),
        default="fr",
        unique=True,
    )

    A11Y_CHOICES = [
        ("FULL", _("fully")),
        ("PART", _("partially")),
        ("NOT", _("not")),
    ]

    # Site
    site_title = models.CharField(
        _("Site title"), max_length=200, default=_("Site title"), blank=True
    )
    site_tagline = models.CharField(
        _("Site tagline"), max_length=200, default=_("Site tagline"), blank=True
    )

    # Notice
    notice_title = models.CharField(
        _("Notice title"),
        max_length=250,
        default="",
        blank=True,
        help_text=_("Can include HTML"),
    )

    notice_description = models.TextField(
        _("Notice description"),
        default="",
        blank=True,
        help_text=_("Can include HTML"),
    )

    notice_type = models.CharField(
        _("Notice type"),
        choices=NOTICE_TYPE_CHOICES,
        default="info",
        blank=True,
        max_length=20,
        help_text=_(
            'Use is strictly regulated, see \
            <a href="https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bandeau-d-information-importante/">documentation</a>.'
        ),
    )

    notice_link = models.URLField(
        _("Notice link"),
        default="",
        blank=True,
        help_text=_("Standardized consultation link at the end of the notice."),
    )

    notice_icon_class = models.CharField(
        _("Notice icon class"),
        max_length=200,
        default="",
        blank=True,
        help_text=_("For weather alerts only"),
    )

    notice_is_collapsible = models.BooleanField(_("Collapsible?"), default=False)  # type: ignore

    # Header
    header_brand = models.CharField(
        _("Institution (header)"),
        max_length=200,
        default="République française",
        blank=True,
    )
    header_brand_html = models.CharField(
        _("Institution with line break (header)"),
        max_length=200,
        default="République<br />française",
        blank=True,
    )
    beta_tag = models.BooleanField(_("Show the BETA tag next to the title"), default=False)  # type: ignore

    # Footer
    footer_brand = models.CharField(
        _("Institution (footer)"),
        max_length=200,
        default="République française",
        blank=True,
    )
    footer_brand_html = models.CharField(
        _("Institution with line break (footer)"),
        max_length=200,
        default="République<br />française",
        blank=True,
    )
    footer_description = models.TextField(_("Description"), default="", blank=True)

    newsletter_description = models.TextField(
        _("Newsletter description"), default="", blank=True
    )

    newsletter_url = models.URLField(
        _("Newsletter registration URL"),
        default="",
        blank=True,
    )

    # Operator logo
    operator_logo_file = models.FileField(
        _("Operator logo"),
        upload_to="logos",
        blank=True,
        null=True,
        validators=[validate_image_extension],
    )
    operator_logo_alt = models.CharField(
        _("Logo alt text"),
        max_length=200,
        blank=True,
        help_text=_("Must contain the text present in the image."),
    )
    operator_logo_width = models.DecimalField(
        _("Width (em)"),
        max_digits=3,
        decimal_places=1,
        null=True,
        default="0.0",
        help_text=_(
            "To be adjusted according to the width of the logo.\
            Example for a vertical logo: 3.5, Example for a horizontal logo: 8."
        ),
    )

    # Advanced
    mourning = models.BooleanField(_("Mourning"), default=False)  # type: ignore

    accessibility_status = models.CharField(
        _("Accessibility compliance status"),
        max_length=4,
        choices=A11Y_CHOICES,
        default="NOT",
    )

    class Meta:
        verbose_name = _("Configuration")

    def __str__(self):
        return _("Site config:") + f" {self.site_title} ({self.language})"

    def social_media(self):
        return self.dsfrsocialmedia_set.all()


class DsfrSocialMedia(models.Model):
    site_config = models.ForeignKey(DsfrConfig, on_delete=models.CASCADE, null=True)
    title = models.CharField(_("Title"), max_length=200, default="", blank=True)

    url = models.URLField(
        _("URL"),
        default="",
        blank=True,
    )
    icon_class = models.CharField(
        _("Icon class"), max_length=200, default="", blank=True
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _("Social media")
        verbose_name_plural = _("Social medias")

dsfr/forms.py
import warnings
from pathlib import Path

from django import forms
from django.forms.renderers import DjangoTemplates, get_default_renderer
from django.utils.functional import cached_property

from .utils import dsfr_input_class_attr


class DsfrDjangoTemplates(DjangoTemplates):
    @cached_property
    def engine(self):
        return self.backend(
            {
                "APP_DIRS": True,
                "DIRS": [
                    Path(__file__).resolve().parent / self.backend.app_dirname,
                    Path(forms.__path__[0]).resolve() / "templates",  # type: ignore
                ],
                "NAME": "djangoforms",
                "OPTIONS": {},
            }  # type: ignore
        )


class DsfrBaseForm(forms.Form):
    """
    A base form that adds the necessary classes on relevant fields
    """

    template_name = "dsfr/form_snippet.html"  # type: ignore

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            dsfr_input_class_attr(visible)

    @property
    def default_renderer(self):
        from django.conf import settings, global_settings

        return (
            DsfrDjangoTemplates  # Settings wasn't modified
            if settings.FORM_RENDERER == global_settings.FORM_RENDERER
            else get_default_renderer()
        )

    def set_autofocus_on_first_error(self):
        """
        Sets the autofocus on the first field with an error message.
        Not included in the __init__ by default because it can cause some side effects on
        non-standard fields/forms.
        """
        for field in self.errors.keys():
            self.fields[field].widget.attrs.update({"autofocus": ""})
            break

dsfr/templates/dsfr/alert.html
{% load i18n %}
{% translate "Hide message" as hide_message %}
<div role="alert"
     class="fr-alert fr-alert--{{ self.type }}{% if self.extra_classes %} {{ self.extra_classes }}{% endif %}">
  {% if self.title %}
    <{{ self.heading_tag | default:"p" }} class="fr-alert__title">{{ self.title }}</{{ self.heading_tag | default:"p" }}>
  {% endif %}
  {% if self.content %}
    <p>
      {{ self.content | safe }}
    </p>
  {% endif %}
  {% if self.is_collapsible %}
    <button class="fr-btn--close fr-btn"
            title="{{ hide_message }}"
            {% for attr, value in self.collapsible_attrs.items %}{{ attr }}="{{ value|safe }}"{% endfor %}>
      {{ hide_message }}
    </button>
  {% endif %}
</div>

dsfr/templates/dsfr/callout.html
{% load dsfr_tags %}
<div class="fr-callout {% if self.icon_class %}{{ self.icon_class }}{% endif %}{% if self.extra_classes %} {{ self.extra_classes }}{% endif %}">
  {% if self.title %}
    <{{ self.heading_tag | default:"p" }} class="fr-callout__title">
    {{ self.title }}
    </{{ self.heading_tag | default:"p" }}>
  {% endif %}
  <p class="fr-callout__text">
    {{ self.text }}
  </p>
  {% if self.button %}
    {% if self.button.onclick %}
      {% dsfr_button self.button %}
    {% elif self.button.url %}
      <a href="{{ self.button.url }}" class="fr-btn">{{ self.button.label }}</a>
    {% endif %}
  {% endif %}
</div>

dsfr/templates/dsfr/consent.html
{% load i18n %}
<div class="fr-consent-banner">
  <h2 class="fr-h6">
    {{ self.title }}
  </h2>
  <div class="fr-consent-banner__content">
    <p class="fr-text--sm">
      {{ self.content|safe }}
    </p>
  </div>
  <ul class="fr-consent-banner__buttons fr-btns-group fr-btns-group--right fr-btns-group--inline-reverse fr-btns-group--inline-sm">
    <li>
      {% translate "Allow all cookies" as allow_all_cookies %}
      <button class="fr-btn"
              id="consent-accept-all"
              title="{{ allow_all_cookies }}">
        {% translate "Accept all" %}
      </button>
    </li>
    <li>
      {% translate "Reject all cookies" as reject_all_cookies %}
      <button class="fr-btn"
              id="consent-reject-all"
              title="{{ reject_all_cookies }}">
        {% translate "Reject all" %}
      </button>
    </li>
    <li>
      {% translate "Customize cookies" as customize_cookies %}
      <button class="fr-btn fr-btn--secondary"
              id="consent-customize"
              data-fr-opened="false"
              aria-controls="fr-consent-modal"
              title="{{ customize_cookies }}">
        {% translate "Customize" %}
      </button>
    </li>
  </ul>
</div>

dsfr/templates/dsfr/footer.html
{% load i18n %}
{% translate "Opens a new window" as new_window_label %}
<footer class="fr-footer" role="contentinfo" id="footer">
  {% block footer_top %}
  {% endblock footer_top %}
  <div class="fr-container">
    <div class="fr-footer__body">
      {% block footer_brand %}
        {% translate "Back to home page" as back_to_home_label %}
        {% if SITE_CONFIG.operator_logo_file and SITE_CONFIG.operator_logo_alt %}
          <div class="fr-footer__brand fr-enlarge-link">
            <p class="fr-logo"
               title="{{ SITE_CONFIG.footer_brand|default:'république française' }}">
              {{ SITE_CONFIG.footer_brand_html| default_if_none:'république<br />française' | safe }}
            </p>
            <a class="fr-footer__brand-link"
               href="/"
               title="{{ back_to_home_label }} - {{ SITE_CONFIG.operator_logo_alt }} - {{ SITE_CONFIG.footer_brand|default:'république française' }}">
              <img class="fr-footer__logo"
                   src="{{ SITE_CONFIG.operator_logo_file.url }}"
                   alt="{{ SITE_CONFIG.operator_logo_alt }}"
                   {% if SITE_CONFIG.operator_logo_width >= 1 %}style="max-width:{{ SITE_CONFIG.operator_logo_width }}rem;"{% endif %} />
              {# L’alternative de l’image (attribut alt) doit impérativement être renseignée et reprendre le texte visible dans l’image #}
            </a>
          </div>
        {% else %}
          <div class="fr-footer__brand fr-enlarge-link">
            <a id="footer-operator"
               href="/"
               title="{{ back_to_home_label }} - {{ SITE_CONFIG.site_title }} - {{ SITE_CONFIG.footer_brand|default:'république française' }}">
              {% block brand %}
                <p class="fr-logo">
                  {{ SITE_CONFIG.footer_brand_html| default_if_none:'république<br />française' | safe }}
                </p>
              {% endblock brand %}
            </a>
          </div>
        {% endif %}
      {% endblock footer_brand %}
      <div class="fr-footer__content">
        {% block footer_description %}
          <p class="fr-footer__content-desc">
            {% block footer_content %}
              {{ SITE_CONFIG.footer_description | safe }}
            {% endblock footer_content %}
          </p>
        {% endblock footer_description %}
        <ul class="fr-footer__content-list">
          <li class="fr-footer__content-item">
            <a target="_blank"
               rel="noopener external"
               title="info.gouv.fr - {{ new_window_label }}"
               id="footer__content-link-gouvernement"
               class="fr-footer__content-link"
               href="https://www.info.gouv.fr">info.gouv.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a target="_blank"
               rel="noopener external"
               title="service-public.gouv.fr - {{ new_window_label }}"
               id="footer__content-link-servicepublic"
               class="fr-footer__content-link"
               href="https://service-public.gouv.fr">service-public.gouv.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a target="_blank"
               rel="noopener external"
               title="legifrance.gouv.fr - {{ new_window_label }}"
               id="footer__content-link-legifrance"
               class="fr-footer__content-link"
               href="https://legifrance.gouv.fr">legifrance.gouv.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a target="_blank"
               rel="noopener external"
               title="data.gouv.fr - {{ new_window_label }}"
               id="footer__content-link-datagouv"
               class="fr-footer__content-link"
               href="https://data.gouv.fr">data.gouv.fr</a>
          </li>
          {% block footer_content_extra %}
          {% endblock footer_content_extra %}
        </ul>
      </div>
    </div>
    {% block footer_partners %}
    {% endblock footer_partners %}
    <div class="fr-footer__bottom">
      <ul class="fr-footer__bottom-list">
        {% block footer_links %}
          <li class="fr-footer__bottom-item">
            {% url 'footer-sitemap' as sitemap_url %}
            <a class="fr-footer__bottom-link" href={% if sitemap_url %}"{{ sitemap_url }}"{% else %}"#"{% endif %} id="footer_sitemap">{% translate "Sitemap" %}</a>
          </li>
          <li class="fr-footer__bottom-item">
            {% url 'footer-accessibility-status' as accessibility_status_url %}
            <a class="fr-footer__bottom-link" href={% if accessibility_status_url %}"{{ accessibility_status_url }}"{% else %}"#"{% endif %} id="footer_accessibility_status">
              {% with accessibility_status=SITE_CONFIG.get_accessibility_status_display|default:"non" %}
                {% blocktranslate %}Accessibility: {{ accessibility_status }} compliant{% endblocktranslate %}
              {% endwith %}
            </a>
          </li>
          <li class="fr-footer__bottom-item">
            {% url 'footer-legal-notice' as legal_notice_url %}
            <a class="fr-footer__bottom-link" href={% if legal_notice_url %}"{{ legal_notice_url }}"{% else %}"#"{% endif %} id="footer_legal_notice">{% translate "Legal notice" %}</a>
          </li>
          <li class="fr-footer__bottom-item">
            {% url 'footer-personal-data' as personal_data_url %}
            <a class="fr-footer__bottom-link" href={% if personal_data_url %}"{{ personal_data_url }}"{% else %}"#"{% endif %} id="footer_personal_data">{% translate "Personal data" %}</a>
          </li>
          <li class="fr-footer__bottom-item">
            {% url 'footer-cookie-management' as cookie_management_url %}
            <a class="fr-footer__bottom-link" href={% if cookie_management_url %}"{{ cookie_management_url }}"{% else %}"#"{% endif %} id="footer_cookie_management">{% translate "Cookie management" %}</a>
          </li>
        {% endblock footer_links %}
      </ul>
      <div class="fr-footer__bottom-copy">
        <p>
          {% translate "etalab-2.0 license" as etalab_license %}
          {% translate "Unless explicit mention of intellectual property held by third parties, the contents of this site are offered under" %}
          <a href="https://github.com/etalab/licence-ouverte/blob/master/LO.md"
             target="_blank"
             rel="noopener external"
             title="{{ etalab_license|capfirst }} - {{ new_window_label }}">{{ etalab_license }}</a>
          {% block footer_bottom_extra %}
          {% endblock footer_bottom_extra %}
        </p>
      </div>
    </div>
  </div>
</footer>

dsfr/templates/dsfr/formset_base.html
<!-- Created on Wed Feb 09 11:14:00 2022 @author: alica.burlot -->
<!-- base template for formset -->
<!-- to be INCLUDED in the templates where form_base.html is extended, if you need formset -->
<!-- Check django comments for more information -->
{# Allows to display the fields with DSFR layout #}
{% load static dsfr_tags widget_tweaks i18n %}
{# if formset #}
{% block form_set %}
  {% if formset %}
    <div class="formset-{{ formset.prefix }} formset-group">
      {{ formset.management_form }}
      {% block formset_title %}
      {% endblock formset_title %}
      {% for form in formset %}
        <div class="{% cycle 'row1' 'row2' %} formset-row-{{ formset.prefix }} formset {% block formset_style %}fr-background-alt--grey fr-px-6v fr-py-6v fr-mb-4v{% endblock formset_style %}"
             id="formset-0">
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
            {# everything that needs to be in the loop for each field for each form in formset #}
            {% block inside_formset_field %}
            {% endblock inside_formset_field %}
            {{ field.as_field_group }}
          {% endfor %}
          <div class="fr-mt-2w">
            <button id="remove-0"
                    type="button"
                    class="fr-btn fr-btn--secondary fr-fi-delete-line fr-btn--icon-right fr-mt-1w"
                    onclick="removeFormset(0)">
              {% translate "Delete this item" %}
            </button>
          </div>
        </div>
      {% endfor %}
      <button id="add-form"
              type="button"
              class="fr-btn fr-btn--secondary fr-fi-add-circle-line fr-btn--icon-right fr-mt-1w">
        {% translate "Add an item" %}
      </button>
    </div>
    <br />
  {% endif %}
{% endblock form_set %}
{% block extra_js %}
  <script>let objectName = "{{ object_name }}";</script>
  <script src="{% static 'js/formsets.js' %}"></script>
{% endblock extra_js %}

dsfr/templates/dsfr/france_connect.html
{% load i18n %}
<div class="fr-connect-group">
  <button class="fr-connect{% if self.plus %} fr-connect--plus{% endif %}"
          id="{{ self.id }}">
    <span class="fr-connect__login">{% translate "Login with" %}</span>
    <span class="fr-connect__brand">FranceConnect</span>
  </button>
  <p>
    {% translate "Opens a new window" as new_window_label %}
    {% translate "What is FranceConnect+?" as what_is_franceconnect_plus %}
    {% translate "What is FranceConnect?" as what_is_franceconnect %}
    {% if self.plus %}
      <a href="https://franceconnect.gouv.fr/france-connect-plus"
         target="_blank"
         rel="noopener"
         title="{{ what_is_franceconnect_plus }} - {{ new_window_label }}">{{ what_is_franceconnect_plus }}</a>
    {% else %}
      <a href="https://franceconnect.gouv.fr/"
         target="_blank"
         rel="noopener"
         title="{{ what_is_franceconnect }} - {{ new_window_label }}">{{ what_is_franceconnect }}</a>
    {% endif %}
  </p>
</div>

dsfr/templates/dsfr/header.html
{% load i18n %}
<header role="banner" class="fr-header">
  <div class="fr-header__body">
    <div class="fr-container">
      <div class="fr-header__body-row">
        <div class="fr-header__brand fr-enlarge-link">
          <div class="fr-header__brand-top">
            <div class="fr-header__logo">
              {% block brand %}
                <p class="fr-logo">
                  {{ SITE_CONFIG.header_brand_html|default_if_none:"république<br />française" | safe }}
                </p>
              {% endblock brand %}
            </div>
            {% block operator_logo %}
              {% if SITE_CONFIG.operator_logo_file and SITE_CONFIG.operator_logo_alt %}
                <div class="fr-header__operator">
                  <img class="fr-responsive-img"
                       src="{{ SITE_CONFIG.operator_logo_file.url }}"
                       alt="{{ SITE_CONFIG.operator_logo_alt }}"
                       {% if SITE_CONFIG.operator_logo_width >= 1 %}style="max-width:{{ SITE_CONFIG.operator_logo_width }}rem;"{% endif %} />
                </div>
              {% endif %}
            {% endblock operator_logo %}
            {% block burger_menu %}
              {% translate "Menu" as menu_label %}
              <div class="fr-header__navbar">
                <button class="fr-btn--menu fr-btn"
                        data-fr-opened="false"
                        aria-controls="fr-menu-mobile"
                        id="fr-btn-menu-mobile"
                        title="{{ menu_label }}">
                  {{ menu_label }}
                </button>
              </div>
            {% endblock burger_menu %}
          </div>
          <div class="fr-header__service">
            {% block service_title %}
              <a href="/" title="Accueil — {{ SITE_CONFIG.site_title }}">
                <p class="fr-header__service-title">
                  {{ SITE_CONFIG.site_title }}
                  {% if SITE_CONFIG.beta_tag %}
                    <span class="fr-badge fr-badge--sm fr-badge--green-emeraude">BETA</span>
                  {% endif %}
                </p>
              </a>
            {% endblock service_title %}
            <p class="fr-header__service-tagline">
              {% block service_tagline %}
                {{ SITE_CONFIG.site_tagline }}
              {% endblock service_tagline %}
            </p>
          </div>
        </div>
        {% block header_tools_wrapper %}
          <div class="fr-header__tools">
            {% block header_tools_links %}
              <div class="fr-header__tools-links">
                <ul class="fr-btns-group">
                  {% block header_tools %}
                    <li>
                      <a class="fr-icon-add-circle-line fr-btn" href="[url - à modifier]">Créer un espace</a>
                    </li>
                    <li>
                      <a class="fr-icon-lock-line fr-btn" href="[url - à modifier]">Se connecter</a>
                    </li>
                    <li>
                      <a class="fr-icon-account-line fr-btn" href="[url - à modifier]">S’enregistrer</a>
                    </li>
                  {% endblock header_tools %}
                </ul>
              </div>
            {% endblock header_tools_links %}
            {% block header_search %}
            {% endblock header_search %}
          </div>
        {% endblock header_tools_wrapper %}
      </div>
    </div>
  </div>
  {% block main_menu %}
    <div class="fr-header__menu fr-modal"
         id="fr-menu-mobile"
         aria-labelledby="fr-btn-menu-mobile">
      <div class="fr-container">
        <button class="fr-btn--close fr-btn" aria-controls="fr-menu-mobile">
          {% translate "Close" %}
        </button>
        <div class="fr-header__menu-links">
        </div>
        {% translate "Main menu" as main_menu_label %}
        <nav role="navigation"
             class="fr-nav"
             id="fr-navigation"
             aria-label="{{ main_menu_label }}">
          <ul class="fr-nav__list">
            <li class="fr-nav__item">
              <a class="fr-nav__link" href="#" target="_self">accès direct</a>
            </li>
            <li class="fr-nav__item">
              <a class="fr-nav__link" href="#" target="_self">accès direct</a>
            </li>
            <li class="fr-nav__item">
              <a class="fr-nav__link" href="#" target="_self">accès direct</a>
            </li>
            <li class="fr-nav__item">
              <a class="fr-nav__link" href="#" target="_self">accès direct</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  {% endblock main_menu %}
</header>

dsfr/templates/dsfr/highlight.html
<div class="fr-highlight{% if self.extra_classes %} {{ self.extra_classes }}{% endif %}">
  <p {% if self.size_class %}class="{{ self.size_class }}"{% endif %}>
    {{ self.content | safe }}
  </p>
</div>

dsfr/templates/dsfr/notice.html
{% load i18n %}
{% translate "Hide message" as hide_message %}
{% translate "Consultation link" as consultation_link %}
{% translate "Opens a new window" as new_window_label %}
<div class="fr-notice fr-notice--{{ self.type|default:'info' }}">
  <div class="fr-container">
    <div class="fr-notice__body">
      <p>
        <span class="fr-notice__title{% if self.icon %} {{ self.icon }}{% endif %}">{{ self.title|safe }}</span>
        {% if self.description %}
          <span class="fr-notice__desc">{{ self.description|safe }}</span>
        {% endif %}
        {% if self.link %}
          <a target="_blank"
             rel="noopener external"
             title="{{ consultation_link }} - {{ new_window_label }}"
             href="{{ self.link }}"
             class="fr-notice__link">{{ consultation_link }}</a>
        {% endif %}
      </p>
      {% if self.is_collapsible %}
        <button class="fr-btn--close fr-btn"
                title="{{ hide_message }}"
                onclick="const notice = this.parentNode.parentNode.parentNode; notice.parentNode.removeChild(notice)">
          {{ hide_message }}
        </button>
      {% endif %}
    </div>
  </div>
</div>

dsfr/templates/dsfr/quote.html
{% load i18n %}
{% translate "Opens a new window" as new_window_label %}
<figure class="fr-quote fr-quote--column{% if self.extra_classes %} {{ self.extra_classes }}{% endif %}">
  <blockquote {% if self.source_url %}cite="{{ self.source_url }}"{% endif %}>
    <p>
      {{ self.text }}
    </p>
  </blockquote>
  <figcaption>
    {% if self.author %}
      <p class="fr-quote__author">
        {{ self.author }}
      </p>
    {% endif %}
    {% if self.details or self.source %}
      <ul class="fr-quote__source">
        <li>
          <cite>{{ self.source }}</cite>
        </li>
        {% for detail in self.details %}
          {% if detail.link %}
            <li>
              <a target="_blank" rel="noopener noreferrer" href="{{ detail.link }}">{{ detail.text }} <span class="fr-sr-only">{{ new_window_label }}</span></a>
            </li>
          {% else %}
            <li>
              {{ detail.text }}
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    {% endif %}
    {% if self.image_url %}
      <div class="fr-quote__image">
        <img src="{{ self.image_url }}" class="fr-responsive-img" alt="" />
      </div>
    {% endif %}
  </figcaption>
</figure>

dsfr/templates/dsfr/select.html
<div class="fr-select-group {% if self.extra_classes %}{{ self.extra_classes }}{% endif %}">
  <label class="fr-label" for="{{ self.id }}">
    {{ self.label }}
    {% if self.hint %}<span class="fr-hint-text">{{ self.hint }}</span>{% endif %}
  </label>
  <select class="fr-select"
          id="{{ self.id }}"
          name="{{ self.id }}"
          {% if self.onchange %}onchange="{{ self.onchange }}"{% endif %}>
    {% if self.default %}
      <option value="{{ self.default.value }}"
              {% if self.selected == None %}selected{% endif %}
              {% if self.default.disabled %}disabled{% endif %}
              {% if self.default.hidden %}hidden{% endif %}>
        {{ self.default.text }}
      </option>
    {% endif %}
    {% for option in self.options %}
      <option value="{{ option.value }}"
              {% if self.selected == option.value %}selected{% endif %}>
        {{ option.text }}
      </option>
    {% endfor %}
  </select>
</div>

dsfr/templates/dsfr/skiplinks.html
{% load i18n %}
{% translate "Skip links" as skiplinks_label %}
<div class="fr-skiplinks">
  <nav role="navigation"
       class="fr-container"
       aria-label="{{ skiplinks_label }}">
    <ul class="fr-skiplinks__list">
      {% for item in self.items %}
        <li>
          <a class="fr-link" href="{{ item.link }}">{{ item.label }}</a>
        </li>
      {% endfor %}
    </ul>
  </nav>
</div>

dsfr/templates/dsfr/summary_list.html
<li>
  <a class="fr-summary__link" href="{{ item.link }}">{{ item.label }}</a>
  {% if item.children %}
    <ol>
      {% for child in item.children %}
        {% include "dsfr/summary_list.html" with item=child %}
      {% endfor %}
    </ol>
  {% endif %}
</li>